# set the list of root files containing primaries to import into the primary generator TChain
# be sure that the neutrinosDirectory is set before setting the primariesDirectory!
#/mygen/neutrinosdirectory /home/marc/LinuxSystemFiles/WChSandBox/build/fluxesandtables/gntp.*.ghep.root
#/mygen/primariesdirectory /home/marc/LinuxSystemFiles/WChSandBox/build/fluxesandtables/annie_tank_flux.*.root
#/mygen/neutrinosdirectory /pnfs/annie/persistent/simulations/genie3/G1810a0211a/standard/tank/gntp.*.ghep.root
#/mygen/primariesdirectory /pnfs/annie/persistent/simulations/genie3/G1810a0211a/standard/tank/annie_tank_flux.*.root
#/mygen/neutrinosdirectory /annie/app/users/jminock/genie_shed/gntp.1.ghep.root
#/mygen/primariesdirectory /annie/app/users/jminock/genie_shed/annie_tank_flux.1.root
/mygen/neutrinosdirectory ./gntp.*.ghep.root
/mygen/primariesdirectory ./annie_tank_flux.*.root
/mygen/primariesoffset 0
