# set the list of root files containing primaries to import into the primary generator TChain
# be sure that the neutrinosDirectory is set before setting the primariesDirectory!
#/mygen/neutrinosdirectory /home/marc/LinuxSystemFiles/WChSandBox/build/fluxesandtables/gntp.*.ghep.root
#/mygen/primariesdirectory /home/marc/LinuxSystemFiles/WChSandBox/build/fluxesandtables/annie_tank_flux.*.root
#/mygen/neutrinosdirectory /pnfs/annie/persistent/simulations/nuisance/nuwro/standard/tank/gntp.*.ghep.root
#/mygen/primariesdirectory /pnfs/annie/persistent/simulations/g4dirt/nuwro/standard/tank/annie_tank_flux.*.root
/mygen/neutrinosdirectory ./nui.*.root
/mygen/primariesdirectory ./annie_tank_flux.*.root
/mygen/primariesoffset 0
